<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="estilos.css">
    <title>Document</title>
</head>
<body>
    <div class="contenedor">
        <header>header</header>
        <nav>nav</nav>
        <aside>as</aside>
        <article>article</article>
        <aside>as</aside>
        <footer>foot</footer>
    </div>
</body>
</html>