<?php
session_start();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="estilos.css">
    <title>Foros G</title>
</head>
<body>
    <div class="contenedor">
        <?php include'partes/header.php' ?>
        <aside></aside>
        <article>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam distinctio veniam, perspiciatis minima, alias voluptatem aliquam laborum culpa minus corporis natus vitae dolorem nobis similique eaque. Laboriosam dolores voluptate exercitationem?
            Rerum animi nihil ipsum! Optio odit qui dolore officia doloribus neque nisi veritatis, saepe voluptate, itaque quidem in ea hic iure repudiandae obcaecati! Eligendi veritatis debitis alias aliquam, minima et?
            Aspernatur quas placeat qui temporibus ut voluptas laborum quidem sint, nihil fugit omnis quae incidunt! Repellat, maiores vel, nobis amet at excepturi autem voluptates, maxime rem ratione tempore accusantium? Ab?
            Officiis perspiciatis doloribus officia a pariatur expedita consequuntur. Qui nulla sunt nemo id temporibus mollitia recusandae numquam eveniet, dolores ex ipsa ut fugiat reiciendis placeat quasi voluptatem veniam eaque magnam!
            Distinctio, officia corporis ducimus, facere in perspiciatis soluta deserunt quidem omnis quas necessitatibus quos ullam hic eveniet sequi excepturi earum nisi nam asperiores dolorem atque? Minima earum in maxime mollitia.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium voluptas ipsam sit consequatur molestias odit corporis ullam! Aperiam eius, iste distinctio accusantium cumque corporis cum iure porro necessitatibus eligendi ea.
            Error delectus facilis id et unde deserunt nisi, debitis eveniet exercitationem at repudiandae omnis ipsam cum cupiditate porro dolores, assumenda mollitia quaerat? Odit delectus facilis in placeat eos accusamus nam!
            Aliquam porro veniam molestiae nostrum quos sit ipsum, qui corrupti ipsam ex, commodi quisquam incidunt, quam quis impedit! Similique, minima saepe autem consequuntur harum rem nulla sit ea at reiciendis.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est qui veritatis nam voluptas vero nisi eos porro vitae provident ipsa eaque neque voluptatibus excepturi animi repellat, placeat, debitis, harum molestias.
            Ipsum unde corrupti eveniet exercitationem ipsa vero temporibus, tenetur enim iure necessitatibus modi saepe aut assumenda reiciendis at, totam officia, sapiente velit repudiandae repellendus. Asperiores illo unde obcaecati a dolorem?
            Ut et dolorem maxime nesciunt temporibus, ullam laboriosam sapiente sed porro fugiat ea aut! Eum, dignissimos? Veniam pariatur consectetur ipsa, explicabo maiores expedita iure, ratione, modi nulla aliquid sunt deserunt?
            Officia delectus dolore consequuntur doloribus recusandae. Placeat voluptates culpa eius, velit ab magnam sint accusantium quisquam vitae pariatur vero eos ipsam minima esse? Hic, soluta! Eveniet labore numquam deserunt hic.
            Velit dicta eveniet optio vel iure eaque inventore nulla illum rem natus blanditiis quo accusantium, ut suscipit tenetur sunt tempore quam aspernatur. Quod, iure eligendi ducimus eos possimus non perspiciatis!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum eius neque dolore, ipsam quia ipsum dolor distinctio reprehenderit aliquam! Explicabo hic et magnam harum earum deleniti repellat possimus distinctio iusto!
            Ex saepe earum velit, harum dolorum explicabo veniam. Delectus dignissimos eum placeat id quaerat facere sapiente. Sed nesciunt quasi nam iure esse assumenda accusantium. Earum incidunt eum reiciendis vitae ex.
            Nesciunt quidem natus autem, atque neque aliquid delectus enim illo eligendi voluptates qui exercitationem libero, hic facere quo? Sunt libero eos, omnis porro fuga neque laboriosam perspiciatis in quis rem!
        </article>
        <aside></aside>
        <?php include'partes/footer.php' ?>
    </div>
</body>
</html>