<?php
session_start();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="estilos.css">
    <title>Foros G</title>
</head>
<body>
    <div class="contenedor">
        <?php include'partes/header.php' ?>
        <article>
            <div class="inicio">
            </div>
            <div class="espacio"></div>
            <div class="foros">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda consectetur perferendis placeat, tempore, velit modi eius delectus neque, inventore eos ipsam optio ut facilis ex dignissimos dolorem ullam incidunt necessitatibus?
                In non corporis laborum a magnam minus illum harum alias suscipit totam. Distinctio molestiae officiis ut eius repudiandae quisquam nobis provident aperiam neque eaque ex itaque, corrupti doloribus? Ipsa, at!
                Quam cupiditate similique deserunt distinctio. Temporibus nesciunt maxime aliquam nihil soluta iusto deleniti laudantium dicta quas quasi dolorum commodi, natus dolore modi a, corporis deserunt vel ducimus in ipsam sequi?
            </div>
        </article>
        <?php include'partes/footer.php' ?>
    </div>
</body>
</html>